/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'bioSections' : Array<BioSection>,
  'socialLinks' : SocialLinks,
  'email' : string,
  'portraitUrl' : string,
}
export interface BioSection { 'body' : string, 'heading' : string }
export type Category = { 'forest_field_notes' : null } |
  { 'personal_essays' : null } |
  { 'beyond_cutoff' : null } |
  { 'wild_within' : null } |
  { 'international_relations' : null };
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'uploadTimestamp' : bigint,
  'filename' : string,
  'sizeBytes' : bigint,
}
export interface Post {
  'metaDescription' : [] | [string],
  'title' : string,
  'subcategory' : [] | [string],
  'body' : string,
  'featuredImage' : [] | [string],
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'readingTimeMinutes' : bigint,
  'isDraft' : boolean,
  'isFeatured' : boolean,
  'excerpt' : string,
  'category' : Category,
}
export interface Quote {
  'text' : string,
  'isActive' : boolean,
  'author' : string,
}
export interface ReadingRecommendation {
  'title' : string,
  'link' : [] | [string],
  'description' : string,
  'author' : string,
  'genre' : string,
  'addedAt' : bigint,
}
export interface SiteSettings {
  'headingFont' : string,
  'section2Description' : string,
  'footerTagline' : string,
  'section1Label' : string,
  'borderRadius' : string,
  'section2Title' : string,
  'footerEmail' : string,
  'heroCtaSecondary' : string,
  'containerMaxWidth' : string,
  'colorCard' : string,
  'colorBorder' : string,
  'aboutPortraitUrl' : string,
  'aboutPreviewText1' : string,
  'aboutPreviewText2' : string,
  'footerInstagram' : string,
  'colorMuted' : string,
  'section4Label' : string,
  'aboutPreviewName' : string,
  'footerQuoteAuthor' : string,
  'section5Title' : string,
  'baseFontSize' : string,
  'section3Description' : string,
  'sectionPadding' : string,
  'colorForeground' : string,
  'footerLinkedin' : string,
  'footerDescription' : string,
  'section2Label' : string,
  'aboutPreviewSubtitle' : string,
  'section3Title' : string,
  'colorBackground' : string,
  'siteName' : string,
  'section4Description' : string,
  'siteSubtitle' : string,
  'section5Label' : string,
  'section1Title' : string,
  'heroCtaPrimary' : string,
  'colorPrimary' : string,
  'section1Description' : string,
  'bodyFont' : string,
  'footerCopyright' : string,
  'section5Description' : string,
  'heroOverlayOpacity' : string,
  'heroTitle' : string,
  'section3Label' : string,
  'section4Title' : string,
  'footerQuoteText' : string,
  'heroEyebrow' : string,
  'heroTagline' : string,
  'footerTwitter' : string,
}
export interface SocialLinks {
  'linkedin' : string,
  'twitter' : string,
  'instagram' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addFileMetadata' : ActorMethod<[FileMetadata], undefined>,
  'addRecommendation' : ActorMethod<[ReadingRecommendation], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'createQuote' : ActorMethod<[string, string], undefined>,
  'deleteFileMetadata' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteRecommendation' : ActorMethod<[string], undefined>,
  'getAboutContent' : ActorMethod<[], [] | [AboutContent]>,
  'getActiveQuote' : ActorMethod<[], [] | [Quote]>,
  'getFeaturedPosts' : ActorMethod<[], Array<Post>>,
  'getFileById' : ActorMethod<[string], [] | [FileMetadata]>,
  'getLatestPosts' : ActorMethod<[bigint], Array<Post>>,
  'getPostBySlug' : ActorMethod<[string], [] | [Post]>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'initialize' : ActorMethod<[], undefined>,
  'isInitialized' : ActorMethod<[], boolean>,
  'listAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'listAllPosts' : ActorMethod<[], Array<Post>>,
  'listFilesByType' : ActorMethod<[string], Array<FileMetadata>>,
  'listPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'listPostsByTag' : ActorMethod<[string], Array<Post>>,
  'listQuotes' : ActorMethod<[], Array<Quote>>,
  'listRecommendations' : ActorMethod<[], Array<ReadingRecommendation>>,
  'listRecommendationsByGenre' : ActorMethod<
    [string],
    Array<ReadingRecommendation>
  >,
  'listSubscribers' : ActorMethod<[], Array<string>>,
  'replaceAllFiles' : ActorMethod<[Array<FileMetadata>], undefined>,
  'setAboutContent' : ActorMethod<[AboutContent], undefined>,
  'setActiveQuote' : ActorMethod<[string, string], undefined>,
  'setSiteSettings' : ActorMethod<[SiteSettings], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'toggleDraft' : ActorMethod<[string], undefined>,
  'toggleFeatured' : ActorMethod<[string], undefined>,
  'updateFileMetadata' : ActorMethod<[string, FileMetadata], undefined>,
  'updatePost' : ActorMethod<[string, Post], undefined>,
  'updateRecommendation' : ActorMethod<
    [string, ReadingRecommendation],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];