/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReadingRecommendation = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Text,
  'genre' : IDL.Text,
  'addedAt' : IDL.Int,
});
export const Category = IDL.Variant({
  'forest_field_notes' : IDL.Null,
  'personal_essays' : IDL.Null,
  'beyond_cutoff' : IDL.Null,
  'wild_within' : IDL.Null,
  'international_relations' : IDL.Null,
});
export const Post = IDL.Record({
  'metaDescription' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'subcategory' : IDL.Opt(IDL.Text),
  'body' : IDL.Text,
  'featuredImage' : IDL.Opt(IDL.Text),
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'readingTimeMinutes' : IDL.Nat,
  'isDraft' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const Quote = IDL.Record({
  'text' : IDL.Text,
  'isActive' : IDL.Bool,
  'author' : IDL.Text,
});

export const idlService = IDL.Service({
  'addRecommendation' : IDL.Func([ReadingRecommendation], [], []),
  'createPost' : IDL.Func([Post], [], []),
  'createQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
  'getActiveQuote' : IDL.Func([], [IDL.Opt(Quote)], ['query']),
  'getFeaturedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getLatestPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isInitialized' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'listPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'listPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'listQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
  'listRecommendations' : IDL.Func(
      [],
      [IDL.Vec(ReadingRecommendation)],
      ['query'],
    ),
  'listRecommendationsByGenre' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReadingRecommendation)],
      ['query'],
    ),
  'listSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'setActiveQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
  'toggleDraft' : IDL.Func([IDL.Text], [], []),
  'toggleFeatured' : IDL.Func([IDL.Text], [], []),
  'updatePost' : IDL.Func([IDL.Text, Post], [], []),
  'updateRecommendation' : IDL.Func([IDL.Text, ReadingRecommendation], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReadingRecommendation = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Text,
    'genre' : IDL.Text,
    'addedAt' : IDL.Int,
  });
  const Category = IDL.Variant({
    'forest_field_notes' : IDL.Null,
    'personal_essays' : IDL.Null,
    'beyond_cutoff' : IDL.Null,
    'wild_within' : IDL.Null,
    'international_relations' : IDL.Null,
  });
  const Post = IDL.Record({
    'metaDescription' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'subcategory' : IDL.Opt(IDL.Text),
    'body' : IDL.Text,
    'featuredImage' : IDL.Opt(IDL.Text),
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'readingTimeMinutes' : IDL.Nat,
    'isDraft' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const Quote = IDL.Record({
    'text' : IDL.Text,
    'isActive' : IDL.Bool,
    'author' : IDL.Text,
  });
  
  return IDL.Service({
    'addRecommendation' : IDL.Func([ReadingRecommendation], [], []),
    'createPost' : IDL.Func([Post], [], []),
    'createQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteRecommendation' : IDL.Func([IDL.Text], [], []),
    'getActiveQuote' : IDL.Func([], [IDL.Opt(Quote)], ['query']),
    'getFeaturedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getLatestPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getPostBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isInitialized' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'listPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'listPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'listQuotes' : IDL.Func([], [IDL.Vec(Quote)], ['query']),
    'listRecommendations' : IDL.Func(
        [],
        [IDL.Vec(ReadingRecommendation)],
        ['query'],
      ),
    'listRecommendationsByGenre' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReadingRecommendation)],
        ['query'],
      ),
    'listSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'setActiveQuote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [], []),
    'toggleDraft' : IDL.Func([IDL.Text], [], []),
    'toggleFeatured' : IDL.Func([IDL.Text], [], []),
    'updatePost' : IDL.Func([IDL.Text, Post], [], []),
    'updateRecommendation' : IDL.Func(
        [IDL.Text, ReadingRecommendation],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };