/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'forest_field_notes' : null } |
  { 'personal_essays' : null } |
  { 'beyond_cutoff' : null } |
  { 'wild_within' : null } |
  { 'international_relations' : null };
export interface Post {
  'metaDescription' : [] | [string],
  'title' : string,
  'subcategory' : [] | [string],
  'body' : string,
  'featuredImage' : [] | [string],
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'readingTimeMinutes' : bigint,
  'isDraft' : boolean,
  'isFeatured' : boolean,
  'excerpt' : string,
  'category' : Category,
}
export interface Quote {
  'text' : string,
  'isActive' : boolean,
  'author' : string,
}
export interface ReadingRecommendation {
  'title' : string,
  'link' : [] | [string],
  'description' : string,
  'author' : string,
  'genre' : string,
  'addedAt' : bigint,
}
export interface _SERVICE {
  'addRecommendation' : ActorMethod<[ReadingRecommendation], undefined>,
  'createPost' : ActorMethod<[Post], undefined>,
  'createQuote' : ActorMethod<[string, string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteRecommendation' : ActorMethod<[string], undefined>,
  'getActiveQuote' : ActorMethod<[], [] | [Quote]>,
  'getFeaturedPosts' : ActorMethod<[], Array<Post>>,
  'getLatestPosts' : ActorMethod<[bigint], Array<Post>>,
  'getPostBySlug' : ActorMethod<[string], [] | [Post]>,
  'initialize' : ActorMethod<[], undefined>,
  'isInitialized' : ActorMethod<[], boolean>,
  'listAllPosts' : ActorMethod<[], Array<Post>>,
  'listPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'listPostsByTag' : ActorMethod<[string], Array<Post>>,
  'listQuotes' : ActorMethod<[], Array<Quote>>,
  'listRecommendations' : ActorMethod<[], Array<ReadingRecommendation>>,
  'listRecommendationsByGenre' : ActorMethod<
    [string],
    Array<ReadingRecommendation>
  >,
  'listSubscribers' : ActorMethod<[], Array<string>>,
  'setActiveQuote' : ActorMethod<[string, string], undefined>,
  'subscribeNewsletter' : ActorMethod<[string], undefined>,
  'toggleDraft' : ActorMethod<[string], undefined>,
  'toggleFeatured' : ActorMethod<[string], undefined>,
  'updatePost' : ActorMethod<[string, Post], undefined>,
  'updateRecommendation' : ActorMethod<
    [string, ReadingRecommendation],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];