/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Quote {
    text: string;
    isActive: boolean;
    author: string;
}
export interface Post {
    metaDescription?: string;
    title: string;
    subcategory?: string;
    body: string;
    featuredImage?: string;
    slug: string;
    tags: Array<string>;
    publishedAt: bigint;
    readingTimeMinutes: bigint;
    isDraft: boolean;
    isFeatured: boolean;
    excerpt: string;
    category: Category;
}
export interface ReadingRecommendation {
    title: string;
    link?: string;
    description: string;
    author: string;
    genre: string;
    addedAt: bigint;
}
export enum Category {
    forest_field_notes = "forest_field_notes",
    personal_essays = "personal_essays",
    beyond_cutoff = "beyond_cutoff",
    wild_within = "wild_within",
    international_relations = "international_relations"
}
export interface backendInterface {
    addRecommendation(recommendation: ReadingRecommendation): Promise<void>;
    createPost(post: Post): Promise<void>;
    createQuote(text: string, author: string): Promise<void>;
    deletePost(slug: string): Promise<void>;
    deleteRecommendation(title: string): Promise<void>;
    getActiveQuote(): Promise<Quote | null>;
    getFeaturedPosts(): Promise<Array<Post>>;
    getLatestPosts(limit: bigint): Promise<Array<Post>>;
    getPostBySlug(slug: string): Promise<Post | null>;
    initialize(): Promise<void>;
    isInitialized(): Promise<boolean>;
    listAllPosts(): Promise<Array<Post>>;
    listPostsByCategory(category: Category): Promise<Array<Post>>;
    listPostsByTag(tag: string): Promise<Array<Post>>;
    listQuotes(): Promise<Array<Quote>>;
    listRecommendations(): Promise<Array<ReadingRecommendation>>;
    listRecommendationsByGenre(genre: string): Promise<Array<ReadingRecommendation>>;
    listSubscribers(): Promise<Array<string>>;
    setActiveQuote(text: string, author: string): Promise<void>;
    subscribeNewsletter(email: string): Promise<void>;
    toggleDraft(slug: string): Promise<void>;
    toggleFeatured(slug: string): Promise<void>;
    updatePost(slug: string, updatedPost: Post): Promise<void>;
    updateRecommendation(title: string, updatedRecommendation: ReadingRecommendation): Promise<void>;
}
import type { Category as _Category, Post as _Post, Quote as _Quote, ReadingRecommendation as _ReadingRecommendation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addRecommendation(arg0: ReadingRecommendation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRecommendation(to_candid_ReadingRecommendation_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRecommendation(to_candid_ReadingRecommendation_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createPost(arg0: Post): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(to_candid_Post_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(to_candid_Post_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createQuote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuote(arg0, arg1);
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteRecommendation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecommendation(arg0);
            return result;
        }
    }
    async getActiveQuote(): Promise<Quote | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveQuote();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveQuote();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeaturedPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedPosts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedPosts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestPosts(arg0: bigint): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestPosts(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestPosts(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostBySlug(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostBySlug(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostBySlug(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isInitialized(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isInitialized();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isInitialized();
            return result;
        }
    }
    async listAllPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPosts();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPosts();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPostsByCategory(arg0: Category): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPostsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPostsByCategory(to_candid_Category_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPostsByTag(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPostsByTag(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPostsByTag(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuotes(): Promise<Array<Quote>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuotes();
            return result;
        }
    }
    async listRecommendations(): Promise<Array<ReadingRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecommendations();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecommendations();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRecommendationsByGenre(arg0: string): Promise<Array<ReadingRecommendation>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecommendationsByGenre(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecommendationsByGenre(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSubscribers(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSubscribers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSubscribers();
            return result;
        }
    }
    async setActiveQuote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveQuote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveQuote(arg0, arg1);
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return result;
        }
    }
    async toggleDraft(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDraft(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDraft(arg0);
            return result;
        }
    }
    async toggleFeatured(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleFeatured(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleFeatured(arg0);
            return result;
        }
    }
    async updatePost(arg0: string, arg1: Post): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePost(arg0, to_candid_Post_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePost(arg0, to_candid_Post_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateRecommendation(arg0: string, arg1: ReadingRecommendation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecommendation(arg0, to_candid_ReadingRecommendation_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecommendation(arg0, to_candid_ReadingRecommendation_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Category_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Post_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Post): Post {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ReadingRecommendation_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReadingRecommendation): ReadingRecommendation {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : from_candid_Post_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Quote]): Quote | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription: [] | [string];
    title: string;
    subcategory: [] | [string];
    body: string;
    featuredImage: [] | [string];
    slug: string;
    tags: Array<string>;
    publishedAt: bigint;
    readingTimeMinutes: bigint;
    isDraft: boolean;
    isFeatured: boolean;
    excerpt: string;
    category: _Category;
}): {
    metaDescription?: string;
    title: string;
    subcategory?: string;
    body: string;
    featuredImage?: string;
    slug: string;
    tags: Array<string>;
    publishedAt: bigint;
    readingTimeMinutes: bigint;
    isDraft: boolean;
    isFeatured: boolean;
    excerpt: string;
    category: Category;
} {
    return {
        metaDescription: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.metaDescription)),
        title: value.title,
        subcategory: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.subcategory)),
        body: value.body,
        featuredImage: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.featuredImage)),
        slug: value.slug,
        tags: value.tags,
        publishedAt: value.publishedAt,
        readingTimeMinutes: value.readingTimeMinutes,
        isDraft: value.isDraft,
        isFeatured: value.isFeatured,
        excerpt: value.excerpt,
        category: from_candid_Category_n12(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link: [] | [string];
    description: string;
    author: string;
    genre: string;
    addedAt: bigint;
}): {
    title: string;
    link?: string;
    description: string;
    author: string;
    genre: string;
    addedAt: bigint;
} {
    return {
        title: value.title,
        link: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.link)),
        description: value.description,
        author: value.author,
        genre: value.genre,
        addedAt: value.addedAt
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    forest_field_notes: null;
} | {
    personal_essays: null;
} | {
    beyond_cutoff: null;
} | {
    wild_within: null;
} | {
    international_relations: null;
}): Category {
    return "forest_field_notes" in value ? Category.forest_field_notes : "personal_essays" in value ? Category.personal_essays : "beyond_cutoff" in value ? Category.beyond_cutoff : "wild_within" in value ? Category.wild_within : "international_relations" in value ? Category.international_relations : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReadingRecommendation>): Array<ReadingRecommendation> {
    return value.map((x)=>from_candid_ReadingRecommendation_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Post>): Array<Post> {
    return value.map((x)=>from_candid_Post_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Post_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Post): _Post {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ReadingRecommendation_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReadingRecommendation): _ReadingRecommendation {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    link?: string;
    description: string;
    author: string;
    genre: string;
    addedAt: bigint;
}): {
    title: string;
    link: [] | [string];
    description: string;
    author: string;
    genre: string;
    addedAt: bigint;
} {
    return {
        title: value.title,
        link: value.link ? candid_some(value.link) : candid_none(),
        description: value.description,
        author: value.author,
        genre: value.genre,
        addedAt: value.addedAt
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metaDescription?: string;
    title: string;
    subcategory?: string;
    body: string;
    featuredImage?: string;
    slug: string;
    tags: Array<string>;
    publishedAt: bigint;
    readingTimeMinutes: bigint;
    isDraft: boolean;
    isFeatured: boolean;
    excerpt: string;
    category: Category;
}): {
    metaDescription: [] | [string];
    title: string;
    subcategory: [] | [string];
    body: string;
    featuredImage: [] | [string];
    slug: string;
    tags: Array<string>;
    publishedAt: bigint;
    readingTimeMinutes: bigint;
    isDraft: boolean;
    isFeatured: boolean;
    excerpt: string;
    category: _Category;
} {
    return {
        metaDescription: value.metaDescription ? candid_some(value.metaDescription) : candid_none(),
        title: value.title,
        subcategory: value.subcategory ? candid_some(value.subcategory) : candid_none(),
        body: value.body,
        featuredImage: value.featuredImage ? candid_some(value.featuredImage) : candid_none(),
        slug: value.slug,
        tags: value.tags,
        publishedAt: value.publishedAt,
        readingTimeMinutes: value.readingTimeMinutes,
        isDraft: value.isDraft,
        isFeatured: value.isFeatured,
        excerpt: value.excerpt,
        category: to_candid_Category_n5(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    forest_field_notes: null;
} | {
    personal_essays: null;
} | {
    beyond_cutoff: null;
} | {
    wild_within: null;
} | {
    international_relations: null;
} {
    return value == Category.forest_field_notes ? {
        forest_field_notes: null
    } : value == Category.personal_essays ? {
        personal_essays: null
    } : value == Category.beyond_cutoff ? {
        beyond_cutoff: null
    } : value == Category.wild_within ? {
        wild_within: null
    } : value == Category.international_relations ? {
        international_relations: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
